services:
  cdn:
    container_name: cdn
    build:
      context: .
      target: cdn
      dockerfile: ./docker/cdn/Dockerfile
    restart: on-failure
<<<<<<< HEAD
    env_file:
      - app.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
=======
>>>>>>> 22022f0081c75477042da66cd81443ff4401ca37
    volumes:
      - cdn-data:/app/assets
    ports:
      - "13100:3100"

volumes:
  cdn-data:
<<<<<<< HEAD

=======
>>>>>>> 22022f0081c75477042da66cd81443ff4401ca37
