services:
  cdn:
    container_name: cdn
    build:
      context: .
      target: cdn
      dockerfile: ./docker/cdn/Dockerfile
    env_file:
      - ./cdn/app.env
    restart: on-failure
    volumes:
      - cdn-data:/app/assets
    ports:
      - "13100:3100"

volumes:
  cdn-data:
