services:
  cdn:
    container_name: cdn
    build:
      context: .
      target: cdn
      dockerfile: ./docker/cdn/Dockerfile
    restart: on-failure
    env_file:
      - app.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - cdn-data:/app/assets
    ports:
      - "13100:3100"

volumes:
  cdn-data:

